### Lotka-Volterra predator-prey model
## By: Nathan Justice
# Latest Edit: 6/1/15

# Load dependencies
library(deSolve)
library(breakpoint)
library(earlywarnings)
library(ggplot2)

lotVpredPrey <- function(time, initState, params){
  # Function for ordinary differential equations (ODE)
  lotVPPeqs <-function(time, initState, params){
    with(as.list(c(initState, params)),{

      # Lotka-Volterra predator-prey model
      dx <- (alpha * prey) - (beta * prey * predator)
      dy <- (gamma * prey * predator) - (delta * predator)

      # alpha = the growth rate of prey
      # beta = the rate at which predators kill prey
      # delta = the death rate of predators
      # gamma = the rate at which predators increase by consuming prey

      list(c(dx, dy))
    })
  }

  # deSolve method to solve initial value problems (IVP)
  output <- data.frame(ode(y=initState, times=time, func=lotVPPeqs, parms=params)[,-1])

  return(output)
}

## Test-values
#params <- c(alpha=1.5, beta=0.02, delta=0.4, gamma=0.01)
#initState <- c(prey=5, predator=1)
#time <- seq(0, 10, by=1)

## Function call
#data <- lotVpredPrey(time, initState, params)

CENBinfo <- function(){
  return(
    "Desctiption:

    Performs calculations to estimate both the number of break-points and their
    corresponding locations of discrete measurements with the CE method.
    Negative binomial distribution is used to model the over-dispersed discrete (count)
    data. This function supports the simulation of break-point locations in the CE
    algorithm based on either the four parameter beta distribution or truncated normal
    distribution. The general BIC is used to select the optimal number of break-points.

    Details:

    The negative binomial (NB) distribution is used to model the discrete (count) data.
    NB model is preferred over the Poisson model when over-dispersion is observed in
    the count data. A performance function score (BIC) is calculated for each of the
    solutions generated by the statistical distribution (four parameter beta distribution
    or truncated normal distribution), which is used to simulate break-points from no
    break-point to the user provided maximum number of break-points. The solution that
    minimizes the BIC with respect to the number of break-points is reported as the optimal
    solution. Finally, a list containing a vector of break-point locations and the number
    of break-points are given in the console.

    References:

    Priyadarshana, W. J. R. M. and Sofronov, G. (2012a) A Modified Cross- Entropy Method for Detecting Multiple Change-Points in DNA Count Data,
    In Proc. of the IEEE Conference on Evolutionary Computation (CEC), 1020-1027,
    DOI: 10.1109/CEC.2012.6256470.

    Priyadarshana, W. J. R. M. and Sofronov, G. (2012b) The Cross-Entropy Method and Multiple Change-Points Detection in Zero-Inflated DNA read count data,
    In: Y. T. Gu, S. C. Saha (Eds.) The 4th International Conference on Computational Methods (ICCM2012), 1-8,
    ISBN 978-1-921897-54-2.

    Rubinstein, R., and Kroese, D. (2004) The Cross-Entropy Method: A Unified
    Approach to Combinatorial Optimization, Monte-Carlo Simulation and Machine Learning.
    Springer-Verlag, New York.

    Schwarz, G. (1978) Estimating the dimension of a model, The Annals of Statistics, 6(2), 461-464."
  )
}

CENORMALinfo <- function(){
  return(
    "Description:

    This function performs calculations to estimate both the number of break-points
    and their corresponding locations of continuous measurements
    with the CE method. The normal distribution is used to model the observed
    continuous data. This function supports the simulation of break-point locations based on
    the four parameter beta distribution and truncated normal distribution.
    The modified BIC proposed by Zhang and Siegmund (2007) is used to select the optimal
    number of break-points.

    Details:

    The normal distribution is used to model the continuous data. A performance function
    score (mBIC) is calculated for each of the solutions generated by the statistical distribution
    (four parameter beta distribution or truncated normal distribution), which is used to simulate
    break-points from no break-point to the user provided maximum number of break-points.
    The solution that maximizes the mBIC with respect to the number of break-points is reported as the
    optimal solution. Finally, a list containing a vector of break-point locations and the number of
    break-points are given in the console.

    References:

    Priyadarshana, W. J. R. M., Sofronov G. (2014) Multiple Break-Points Detection in array CGH Data via the Cross-Entropy Method,
    IEEE/ACM Transactions on Computational Biology and Bioinformatics, no. 1, pp. 1, PrePrints,
    doi:10.1109/TCBB.2014.2361639, ISSN: 1545-5963.

    Priyadarshana, W. J. R. M. and Sofronov, G. (2012) A Modified Cross- Entropy Method for Detecting Multiple Change-Points in DNA Count Data,
    In Proc. of the IEEE Conference on Evolutionary Computation (CEC), 1020-1027,
    DOI: 10.1109/CEC.2012.6256470.

    Rubinstein, R., and Kroese, D. (2004) The Cross-Entropy Method: A Unified Approach to Combinatorial Optimization,
    Monte-Carlo Simulation and Machine Learning. Springer-Verlag, New York.

    Zhang, N.R., and Siegmund, D.O. (2007) A modified Bayes information criterion with applications to the analysis of comparative genomic hybridization data.
    Biometrics, 63, 22-32."
  )
}
